 # 端口配置
server:
  port: 8081

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wttest?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: root
    # 初始化大小，最小，最大
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true

dubbo:
  application:
    name: auth-consumer
  protocol:
    name: dubbo
#注册中心地址
  registry:
    address: zookeeper://127.0.0.1:2181 | zookeeper://127.0.0.1:2182
#调用dubbo组建扫描的项目路径
  scan: com.demo.facade
#telnet端口
  qos:
    port: 22222
#检查服务是否可用默认为true，不可用时抛出异常，阻止spring初始化，为方便部署，可以改成false
 consumer:
    check: false

xxl:
    job:
        executor:
             appname: xxl-job-demo
             ip:
             port: 9999
             logpath: /data/applogs/xxl-job/jobhandler
             logretentiondays: 7
        accessToken:
        admin:
             addresses: http://127.0.0.1:8089/xxl-job-console

logging:
  config: classpath:config/log/log4j2.xml