 # 端口配置
server:
  port: 8082

# 数据库访问配置,主数据源，默认的
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wttest?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: root
    transaction:
        rollback-on-commit-failure: true
    # 初始化大小，最小，最大
    druid:
      initial-size: 10
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # 配置DruidStatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        # IP白名单(没有配置或者为空，则允许所有访问)
        allow: 127.0.0.1
        # IP黑名单 (存在共同时，deny优先于allow)
        deny:
        #  禁用HTML页面上的“Reset All”功能
        reset-enable: false
        # 登录名
        login-username: admin
        # 登录密码
        login-password: 123456

motan :
  #注册中心配置
  registry :
    regProtocol : direct
    address : localhost:9999
    #regProtocol : zookeeper #注册中心协议
    #address : 127.0.0.1:2181 #注册中心地址
    #requestTimeout : 1000 #注册中心连接超时时间(毫秒)
    #connectTimeout : 3000 #注册中心请求超时时间(毫秒)
  #协议配置
  protocol :
    name : motan #协议名称
    minWorkerThread : 20 #最小工作pool线程数
    maxWorkerThread : 50 #最大工作pool线程数
    filter : statistic
  #指定需要解析的包名
  annotation :
    package : com.demo.facade
  #客户端配置
  client :
    protocol : demoMotan
    group : demoGroup
    check : false
    requestTimeout : 30000 #请求超时时间(毫秒)
    connectTimeout : 5000 #连接超时时间(毫秒)
    registry : demoRegistryConfig

#dubbo:
#  application:
#    name: auth-consumer
#  protocol:
#    name: dubbo
##注册中心地址
#  registry:
#    address: zookeeper://127.0.0.1:2181 | zookeeper://127.0.0.1:2182
##调用dubbo组建扫描的项目路径
#  scan: com.demo.facade
##telnet端口
#  qos:
#    port: 22222
##检查服务是否可用默认为true，不可用时抛出异常，阻止spring初始化，为方便部署，可以改成false
# consumer:
#    check: false

logging:
  config : classpath:config/log/log4j2.xml

mybatis:
    config-locations: classpath:mybatisplus.yml